### ISSUE TITLE
non SRD name

### ISSUE THREAD

**Issue by DubhHerder** [Holic75/SolastaExtraContent#1]
Hi, I hope submitting this note is not overstepping.

I saw that you used the name for a subclass that's not covered by the SRD 5.1 content and wanted to suggest that a simple name change might avoid any trouble later. The dev's asked people to avoid using copyrighted content; subclass names such as eldritch knight might fall under that restriction, which would not apply to generalized concepts such as a magic using fighter.

Even changing "eldritch" to "arcane" in the `translations-en.txt` and leaving the code as is could be enough.

Thanks for your work and mods, they add a lot to the game. Please close issue if it's not appropriate.

**Comment by Holic75** [comment]
I do not think wotc has any more rights on term "eldritch knight" than anyone else, since there are plenty of eldritch knights in other systems like pathfinder, and as such, it does not look like it constitutes a DND5 product identity. The description of class is different from the one provided in player's handbook, as well as names and descriptions of its abilities.
